"""add dynamic routes and icons

Revision ID: 191b61b387ab
Revises: b9feb05ea730
Create Date: 2026-05-29 16:27:54.630678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191b61b387ab'
down_revision: Union[str, Sequence[str], None] = 'b9feb05ea730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('svg_content', sa.Text(), nullable=True),
    sa.Column('viewBox', sa.String(length=50), nullable=True),
    sa.Column('color_mode', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icons_category'), 'icons', ['category'], unique=False)
    op.create_index(op.f('ix_icons_id'), 'icons', ['id'], unique=False)
    op.create_index(op.f('ix_icons_name'), 'icons', ['name'], unique=True)
    op.create_index(op.f('ix_icons_uuid'), 'icons', ['uuid'], unique=True)
    op.create_table('dynamic_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('component_path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('icon_color_mode', sa.String(length=50), nullable=True),
    sa.Column('min_hierarchy', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['dynamic_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dynamic_routes_id'), 'dynamic_routes', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_routes_uuid'), 'dynamic_routes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_routes_uuid'), table_name='dynamic_routes')
    op.drop_index(op.f('ix_dynamic_routes_id'), table_name='dynamic_routes')
    op.drop_table('dynamic_routes')
    op.drop_index(op.f('ix_icons_uuid'), table_name='icons')
    op.drop_index(op.f('ix_icons_name'), table_name='icons')
    op.drop_index(op.f('ix_icons_id'), table_name='icons')
    op.drop_index(op.f('ix_icons_category'), table_name='icons')
    op.drop_table('icons')
    # ### end Alembic commands ###
