"""add_notes_to_users

Revision ID: 20035ce19c97
Revises: a979ee4c7455
Create Date: 2026-05-16 22:38:51.078377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20035ce19c97'
down_revision: Union[str, Sequence[str], None] = 'a979ee4c7455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###
