"""add is_active and storage_mode to icons

Revision ID: 3d554d1eed9d
Revises: 87aa31e00c4f
Create Date: 2026-05-29 16:58:10.188369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d554d1eed9d'
down_revision: Union[str, Sequence[str], None] = '87aa31e00c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icons', sa.Column('storage_mode', sa.String(length=50), nullable=True))
    op.add_column('icons', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icons', 'is_active')
    op.drop_column('icons', 'storage_mode')
    # ### end Alembic commands ###
