"""rename level to hierarchy in roles

Revision ID: 4c509c6315b6
Revises: 191b61b387ab
Create Date: 2026-05-29 16:34:25.719988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c509c6315b6'
down_revision: Union[str, Sequence[str], None] = '191b61b387ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'level', new_column_name='hierarchy', existing_type=sa.Integer(), existing_nullable=False)
    op.drop_constraint('uq_roles_level', 'roles', type_='unique')
    op.create_unique_constraint('uq_roles_hierarchy', 'roles', ['hierarchy'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint('uq_roles_hierarchy', 'roles', type_='unique')
    op.create_index(op.f('uq_roles_level'), 'roles', ['level'], unique=True)
    op.drop_column('roles', 'hierarchy')
    # ### end Alembic commands ###
