"""add app_config_globals table

Revision ID: 87aa31e00c4f
Revises: 4c509c6315b6
Create Date: 2026-05-29 16:45:47.364550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aa31e00c4f'
down_revision: Union[str, Sequence[str], None] = '4c509c6315b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config_globals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('color_palette', sa.String(length=100), nullable=False),
    sa.Column('app_scale', sa.Integer(), nullable=False),
    sa.Column('items_per_page', sa.Integer(), nullable=False),
    sa.Column('table_configs', sa.JSON(), nullable=True),
    sa.Column('table_view_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_app_config_globals_id'), 'app_config_globals', ['id'], unique=False)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_app_config_globals_id'), table_name='app_config_globals')
    op.drop_table('app_config_globals')
    # ### end Alembic commands ###
