"""add_token_generated_at_to_users

Revision ID: a711c943d3b9
Revises: e18b40d8cfae
Create Date: 2026-05-17 09:20:53.614262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a711c943d3b9'
down_revision: Union[str, Sequence[str], None] = 'e18b40d8cfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_generated_at')
    # ### end Alembic commands ###
