"""add_uuid_to_users

Revision ID: bd54f88f7f6b
Revises: fc8ebc1f72e6
Create Date: 2026-05-16 22:10:18.077568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd54f88f7f6b'
down_revision: Union[str, Sequence[str], None] = 'fc8ebc1f72e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import uuid
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = [col["name"] for col in inspector.get_columns("users")]
    
    if "uuid" not in existing_columns:
        # 1. Añadir columna como nullable=True
        op.add_column('users', sa.Column('uuid', sa.String(length=36), nullable=True))
        
        # 2. Rellenar los datos existentes
        users_table = sa.Table(
            'users',
            sa.MetaData(),
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('uuid', sa.String(length=36))
        )
        
        results = bind.execute(sa.select(users_table.c.id)).fetchall()
        for row in results:
            bind.execute(
                users_table.update().where(users_table.c.id == row[0]).values(uuid=str(uuid.uuid4()))
            )
        
        # 3. Convertir a nullable=False
        op.alter_column('users', 'uuid', existing_type=sa.String(length=36), nullable=False)
        
        # 4. Reordenar físicamente la columna (solo compatible con MySQL/MariaDB)
        if bind.engine.name in ("mysql", "mariadb"):
            op.execute("ALTER TABLE users MODIFY COLUMN uuid VARCHAR(36) NOT NULL AFTER id")

    # 5. Crear índice si no existe
    existing_indexes = [idx["name"] for idx in inspector.get_indexes("users")]
    if "ix_users_uuid" not in existing_indexes:
        op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
