"""create_password_reset_logs_table

Revision ID: be0c511f5f08
Revises: a711c943d3b9
Create Date: 2026-05-17 09:27:55.189363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0c511f5f08'
down_revision: Union[str, Sequence[str], None] = 'a711c943d3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_logs_id'), 'password_reset_logs', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_logs_token'), 'password_reset_logs', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_logs_user_id'), 'password_reset_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_logs_uuid'), 'password_reset_logs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_logs_uuid'), table_name='password_reset_logs')
    op.drop_index(op.f('ix_password_reset_logs_user_id'), table_name='password_reset_logs')
    op.drop_index(op.f('ix_password_reset_logs_token'), table_name='password_reset_logs')
    op.drop_index(op.f('ix_password_reset_logs_id'), table_name='password_reset_logs')
    op.drop_table('password_reset_logs')
    # ### end Alembic commands ###
