"""add_refresh_token_hash_to_sessions

Revision ID: c8ff02ab0cca
Revises: 6ead75ada07a
Create Date: 2026-05-17 00:00:43.248584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ff02ab0cca'
down_revision: Union[str, Sequence[str], None] = '6ead75ada07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
