"""remove_notes_from_users

Revision ID: cf9fc417a300
Revises: 20035ce19c97
Create Date: 2026-05-16 22:40:07.056688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf9fc417a300'
down_revision: Union[str, Sequence[str], None] = '20035ce19c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
