"""add_confirmation_fields_to_users

Revision ID: e18b40d8cfae
Revises: c8ff02ab0cca
Create Date: 2026-05-17 00:09:26.266434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18b40d8cfae'
down_revision: Union[str, Sequence[str], None] = 'c8ff02ab0cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspect_columns = sa.inspect(conn).get_columns("users")
    column_names = [col["name"] for col in inspect_columns]

    if "token" not in column_names:
        op.add_column('users', sa.Column('token', sa.String(length=255), nullable=True))
        op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    if "confirmed" not in column_names:
        # Usamos server_default='0' (False) para compatibilidad con filas existentes
        op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspect_columns = sa.inspect(conn).get_columns("users")
    column_names = [col["name"] for col in inspect_columns]

    if "token" in column_names:
        op.drop_index(op.f('ix_users_token'), table_name='users')
        op.drop_column('users', 'token')
    if "confirmed" in column_names:
        op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
